### ISSUE TITLE
build and use mongodb driver

### ISSUE THREAD

**Issue by amigo421** [supamii/QttpServer#17]
this is not a bug or feature request, just help needed.
Win10, vc14, x64.
to avoid a pain with a building and installing mongoDB manually, 
(I'm newbie in mongodb),
I've just used usual (for Win) way :  vcpkg install mongo-cxx-driver:x64-windows.
so this was downloaded with a dependencies , built and installed successfully.
however , I don't see there the includes from the example:
`#include <mongo/client/dbclient.h>
`
it contains a number of heades like "mongoc-*.h" and "mongocxx/*.hpp" 

could you clarify how to use mongo driver in a projects instaled via visual c++ package manager? 

thank you

**Comment by supamii** [comment]
ah, well... what is currently supported in documentation is the legacy driver - i will soon take a closer look at the newer and much cooler and fancier driver.

The compiled driver will help you connect with your mongodb.  The driver is something that helps you connect to the database.  Am I making sense?

**Comment by amigo421** [comment]
thank you. actually I understand what is a database driver in terms of a database :) (using this e.g. for sqlite, but not faced with mongodb previously) 
I'd prefer to use one version of the library (mongodb driver in this case) for all projects in the development, and vcpkg is a preferable way for get/build/install libraries on windows. 
my question was for understanding -  what is a difference (between one from qttp package and from project repository one) and why it happened. that are so different .
so if you plan to update qttp copy to upstream , that's enough for me. correct me please if my understanding's wrong
thank you
